-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 15:05:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`TEAM` ;

CREATE TABLE IF NOT EXISTS `db`.`TEAM` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(32) NOT NULL,
  `abbreviation` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `team_id_UNIQUE` ON `db`.`TEAM` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`MANAGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`MANAGER` ;

CREATE TABLE IF NOT EXISTS `db`.`MANAGER` (
  `manager_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `phone` CHAR(9) NULL,
  `email` VARCHAR(128) NULL,
  PRIMARY KEY (`manager_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `manager_id_UNIQUE` ON `db`.`MANAGER` (`manager_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`TEAM_MANAGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`TEAM_MANAGER` ;

CREATE TABLE IF NOT EXISTS `db`.`TEAM_MANAGER` (
  `team_manager_id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`team_manager_id`),
  CONSTRAINT `FK_TEAM_MANAGER__TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `db`.`TEAM` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TEAM_MANAGER__MANAGER`
    FOREIGN KEY (`manager_id`)
    REFERENCES `db`.`MANAGER` (`manager_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `team_manager_id_UNIQUE` ON `db`.`TEAM_MANAGER` (`team_manager_id` ASC) VISIBLE;

CREATE INDEX `FK_TEAM_MANAGER__TEAM_idx` ON `db`.`TEAM_MANAGER` (`team_id` ASC) VISIBLE;

CREATE INDEX `FK_TEAM_MANAGER__MANAGER_idx` ON `db`.`TEAM_MANAGER` (`manager_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`IMAGE` ;

CREATE TABLE IF NOT EXISTS `db`.`IMAGE` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1024) NOT NULL,
  `year` CHAR(4) NULL,
  `link_text` VARCHAR(1024) NULL,
  `comment` VARCHAR(4096) NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `image_id_UNIQUE` ON `db`.`IMAGE` (`image_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`SEASON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`SEASON` ;

CREATE TABLE IF NOT EXISTS `db`.`SEASON` (
  `season_id` INT NOT NULL AUTO_INCREMENT,
  `year` CHAR(4) NOT NULL,
  `team_id` INT NOT NULL,
  `wins` INT NOT NULL,
  `losses` INT NOT NULL,
  `ties` INT NOT NULL,
  `place` INT NOT NULL,
  `away_wins` INT NOT NULL,
  `away_losses` INT NOT NULL,
  `away_ties` INT NOT NULL,
  `home_wins` INT NOT NULL,
  `home_losses` INT NOT NULL,
  `home_ties` INT NOT NULL,
  `runs_scored` INT NOT NULL,
  `runs_allowed` INT NOT NULL,
  PRIMARY KEY (`season_id`),
  CONSTRAINT `FK_SEASON__TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `db`.`TEAM` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `season_id_UNIQUE` ON `db`.`SEASON` (`season_id` ASC) VISIBLE;

CREATE INDEX `FK_SEASON__TEAM_idx` ON `db`.`SEASON` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`COMMISSIONER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`COMMISSIONER` ;

CREATE TABLE IF NOT EXISTS `db`.`COMMISSIONER` (
  `commissioner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `phone` CHAR(9) NULL,
  `email` VARCHAR(128) NULL,
  `assistant` TINYINT NOT NULL DEFAULT 0,
  `co_commissioner` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`commissioner_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `commissioner_id_UNIQUE` ON `db`.`COMMISSIONER` (`commissioner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`COMMISSIONER_SEASON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`COMMISSIONER_SEASON` ;

CREATE TABLE IF NOT EXISTS `db`.`COMMISSIONER_SEASON` (
  `commissioner_season_id` INT NOT NULL AUTO_INCREMENT,
  `commissioner_id` INT NOT NULL,
  `season_id` INT NOT NULL,
  PRIMARY KEY (`commissioner_season_id`),
  CONSTRAINT `FK_COMMISSIONER_SEASON__COMMISSIONER`
    FOREIGN KEY (`commissioner_id`)
    REFERENCES `db`.`COMMISSIONER` (`commissioner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMISSIONER_SEASON__SEASON`
    FOREIGN KEY (`season_id`)
    REFERENCES `db`.`SEASON` (`season_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `commissioner_season_id_UNIQUE` ON `db`.`COMMISSIONER_SEASON` (`commissioner_season_id` ASC) VISIBLE;

CREATE INDEX `FK_COMMISSIONER_SEASON__COMMISSIONER_idx` ON `db`.`COMMISSIONER_SEASON` (`commissioner_id` ASC) VISIBLE;

CREATE INDEX `FK_COMMISSIONER_SEASON__SEASON_idx` ON `db`.`COMMISSIONER_SEASON` (`season_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`SEASON_RESULTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`SEASON_RESULTS` ;

CREATE TABLE IF NOT EXISTS `db`.`SEASON_RESULTS` (
  `season_results_id` INT NOT NULL AUTO_INCREMENT,
  `season_id` INT NOT NULL,
  `season_champs_team_id` INT NULL,
  `tournament_champs_team_id` INT NULL,
  PRIMARY KEY (`season_results_id`),
  CONSTRAINT `FK_SEASON_RESULTS__SEASON`
    FOREIGN KEY (`season_id`)
    REFERENCES `db`.`SEASON` (`season_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `season_results_id_UNIQUE` ON `db`.`SEASON_RESULTS` (`season_results_id` ASC) VISIBLE;

CREATE INDEX `FK_SEASON_RESULTS__SEASON_idx` ON `db`.`SEASON_RESULTS` (`season_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`HALL_OF_FAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`HALL_OF_FAME` ;

CREATE TABLE IF NOT EXISTS `db`.`HALL_OF_FAME` (
  `hall_of_fame_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `image_id` INT NULL,
  `year_inducted` CHAR(4) NOT NULL,
  `comment` VARCHAR(4096) NULL,
  PRIMARY KEY (`hall_of_fame_id`),
  CONSTRAINT `FK_HALL_OF_FAME__IMAGE`
    FOREIGN KEY (`image_id`)
    REFERENCES `db`.`IMAGE` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `hall_of_fame_id_UNIQUE` ON `db`.`HALL_OF_FAME` (`hall_of_fame_id` ASC) VISIBLE;

CREATE INDEX `FK_HALL_OF_FAME__IMAGE_idx` ON `db`.`HALL_OF_FAME` (`image_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db`.`GAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`GAME` ;

CREATE TABLE IF NOT EXISTS `db`.`GAME` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `season_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `week` VARCHAR(16) NOT NULL,
  `field` CHAR(1) NOT NULL,
  `away_team_id` INT NOT NULL,
  `away_score` INT NULL,
  `home_team_id` INT NOT NULL,
  `home_score` INT NULL,
  `umpire_team_id` INT NOT NULL,
  `completed` TINYINT NOT NULL DEFAULT 0,
  `comment` VARCHAR(128) NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `FK_GAME__SEASON`
    FOREIGN KEY (`season_id`)
    REFERENCES `db`.`SEASON` (`season_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GAME__AWAY_TEAM`
    FOREIGN KEY (`away_team_id`)
    REFERENCES `db`.`TEAM` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GAME__HOME_TEAM`
    FOREIGN KEY (`home_team_id`)
    REFERENCES `db`.`TEAM` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GAME__UMPIRE_TEAM`
    FOREIGN KEY (`umpire_team_id`)
    REFERENCES `db`.`TEAM` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `game_id_UNIQUE` ON `db`.`GAME` (`game_id` ASC) VISIBLE;

CREATE INDEX `FK_GAME__SEASON_idx` ON `db`.`GAME` (`season_id` ASC) VISIBLE;

CREATE INDEX `FK_GAME__AWAY_TEAM_idx` ON `db`.`GAME` (`away_team_id` ASC) VISIBLE;

CREATE INDEX `FK_GAME_HOME_TEAM_idx` ON `db`.`GAME` (`home_team_id` ASC) VISIBLE;

CREATE INDEX `FK_GAME__UMPIRE_TEAM_idx` ON `db`.`GAME` (`umpire_team_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
